# Generated by Django 3.2.15 on 2023-06-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_response_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
