# Generated by Django 3.2.15 on 2023-06-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_cpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cpassword',
        ),
    ]
