# Generated by Django 3.2.15 on 2023-06-21 15:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_cpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='exit', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
