# Generated by Django 3.2.15 on 2023-06-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20230618_2315'),
        ('account', '0006_alter_user_phone_number'),
    ]

    operations = [
    ]
