# Generated by Django 3.2.15 on 2022-09-08 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_ad_type', models.CharField(choices=[('rent', 'Rent'), ('pg/hostel', 'PG/Hostel'), ('flatmates', 'Flatmates')], max_length=20)),
                ('single_room', models.BooleanField(default=False)),
                ('double_room', models.BooleanField(default=False)),
                ('triple_room', models.BooleanField(default=False)),
                ('four_room', models.BooleanField(default=False)),
                ('single_room_expected_rent', models.IntegerField(blank=True, null=True)),
                ('single_room_deposit_rent', models.IntegerField(blank=True, null=True)),
                ('single_room_extra_features', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AC', 'AC'), ('TV', 'TV'), ('Cupboard', 'Cupboard'), ('Bedding', 'Bedding'), ('Geyser', 'Geyser'), ('Attached Bathroom', 'Attached Bathroom')], max_length=47, null=True)),
                ('double_room_expected_rent', models.IntegerField(blank=True, null=True)),
                ('double_room_deposit_rent', models.IntegerField(blank=True, null=True)),
                ('double_room_extra_features', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AC', 'AC'), ('TV', 'TV'), ('Cupboard', 'Cupboard'), ('Bedding', 'Bedding'), ('Geyser', 'Geyser'), ('Attached Bathroom', 'Attached Bathroom')], max_length=47, null=True)),
                ('triple_room_expected_rent', models.IntegerField(blank=True, null=True)),
                ('triple_room_deposit_rent', models.IntegerField(blank=True, null=True)),
                ('triple_room_extra_features', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AC', 'AC'), ('TV', 'TV'), ('Cupboard', 'Cupboard'), ('Bedding', 'Bedding'), ('Geyser', 'Geyser'), ('Attached Bathroom', 'Attached Bathroom')], max_length=47, null=True)),
                ('four_room_expected_rent', models.IntegerField(blank=True, null=True)),
                ('four_room_deposit_rent', models.IntegerField(blank=True, null=True)),
                ('four_room_extra_features', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AC', 'AC'), ('TV', 'TV'), ('Cupboard', 'Cupboard'), ('Bedding', 'Bedding'), ('Geyser', 'Geyser'), ('Attached Bathroom', 'Attached Bathroom')], max_length=47, null=True)),
                ('city', models.CharField(choices=[('Kolkata', 'Kolkata'), ('Bangalore', 'Bangalore'), ('Delhi', 'Delhi'), ('Mumbai', 'Mumbai'), ('Chennai', 'Chennai'), ('Pune', 'Pune'), ('Hyderabad', 'Hyderabad'), ('Lucknow', 'Lucknow'), ('Kanpur', 'Kanpur'), ('Ahmedabad', 'Ahmedabad')], max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=100, verbose_name='Landmark/Street')),
                ('pg_name', models.CharField(max_length=100, verbose_name='PG/Hostel Name')),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('pg_available_for', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Anyone', 'Anyone')], max_length=100, verbose_name='PG/Hostel Available For')),
                ('preferred_tenants', models.CharField(choices=[('Girls', 'Girls'), ('Boys', 'Boys'), ('Working Professional', 'Working Professional'), ('Student', 'Student')], max_length=100)),
                ('available_date', models.DateField(blank=True, null=True)),
                ('food_included', models.BooleanField(blank=True, default=False, null=True)),
                ('food_included_details', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=22, null=True)),
                ('gate_closing_time', models.TimeField(blank=True, null=True)),
                ('pg_other_details', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('No Smoking', 'No Smoking'), ('No Guardian', 'No Guardian'), ('No Drinking', 'No Drinking'), ('No Girls Entry', 'No Girls Entry'), ('No Non-Veg', 'No Non-Veg')], max_length=60, null=True)),
                ('pg_other_rules', models.TextField(blank=True, null=True)),
                ('laundry', models.BooleanField(default=False)),
                ('worden', models.BooleanField(default=False)),
                ('room_cleaning', models.BooleanField(default=False)),
                ('parking', models.CharField(blank=True, choices=[('Bike', 'Bike'), ('Four Wheeler', 'Four Wheeler'), ('Bike/Four Wheeler', 'Bike/Four Wheeler')], max_length=100, null=True)),
                ('pg_amenities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('wifi', 'wifi'), ('common tv', 'common tv'), ('lift', 'lift'), ('power backup', 'power backup'), ('mess', 'mess'), ('refrigerator', 'refrigerator'), ('No girls Entry', 'No girls Entry'), ('No boys Entry', 'No boys Entry'), ('No non-veg', 'No non-veg')], max_length=90, null=True)),
                ('property_description', models.TextField(blank=True, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='property_images')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='property_images')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='property_images')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='property_images')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='property_images')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='property_images')),
                ('image_7', models.ImageField(blank=True, null=True, upload_to='property_images')),
                ('image_8', models.ImageField(blank=True, null=True, upload_to='property_images')),
                ('image_9', models.ImageField(blank=True, null=True, upload_to='property_images')),
                ('near_by_railway_station', models.CharField(blank=True, max_length=100, null=True)),
                ('near_by_bus_stand', models.CharField(blank=True, max_length=100, null=True)),
                ('near_by_market', models.CharField(blank=True, max_length=100, null=True)),
                ('near_by_hospital', models.CharField(blank=True, max_length=100, null=True)),
                ('near_by_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('near_by_airport', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
