# Generated by Django 3.2.15 on 2022-09-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='food_included',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='laundry',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='room_cleaning',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='worden',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
