# Generated by Django 3.2.15 on 2022-09-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20220915_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
