# Generated by Django 3.2.15 on 2022-09-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_property_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='pg_other_rules',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
