# Generated by Django 3.2.15 on 2023-06-17 03:58

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20220928_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('Kolkata', 'Kolkata'), ('Bangalore', 'Bangalore'), ('Delhi', 'Delhi'), ('Mumbai', 'Mumbai'), ('Chennai', 'Chennai'), ('Pune', 'Pune'), ('Hyderabad', 'Hyderabad'), ('Lucknow', 'Lucknow'), ('Kanpur', 'Kanpur'), ('Ahmedabad', 'Ahmedabad'), ('Ahmedabad', 'Ahmedabad')], max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='double_room_extra_features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AC', 'AC'), ('TV', 'TV'), ('Cupboard', 'Cupboard'), ('Bedding', 'Bedding'), ('Geyser', 'Geyser'), ('Attached Bathroom', 'Attached Bathroom'), ('Attached Bathroom', 'Attached Bathroom')], max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='four_room_extra_features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AC', 'AC'), ('TV', 'TV'), ('Cupboard', 'Cupboard'), ('Bedding', 'Bedding'), ('Geyser', 'Geyser'), ('Attached Bathroom', 'Attached Bathroom'), ('Attached Bathroom', 'Attached Bathroom')], max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='pg_available_for',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Anyone', 'Anyone'), ('Anyone', 'Anyone')], max_length=100, verbose_name='PG/Hostel Available For'),
        ),
        migrations.AlterField(
            model_name='property',
            name='single_room_extra_features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AC', 'AC'), ('TV', 'TV'), ('Cupboard', 'Cupboard'), ('Bedding', 'Bedding'), ('Geyser', 'Geyser'), ('Attached Bathroom', 'Attached Bathroom'), ('Attached Bathroom', 'Attached Bathroom')], max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='triple_room_extra_features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AC', 'AC'), ('TV', 'TV'), ('Cupboard', 'Cupboard'), ('Bedding', 'Bedding'), ('Geyser', 'Geyser'), ('Attached Bathroom', 'Attached Bathroom'), ('Attached Bathroom', 'Attached Bathroom')], max_length=65, null=True),
        ),
    ]
