# Generated by Django 3.2.15 on 2023-06-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20230617_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
